[workspace]
members = ["binance", "binance_spot_connector", "binance_future_connector", "binance_spot_connector/examples", "binance_future_connector/examples",
    "common", "market", "trade" , "binance_assembler", "log", "ctp", "ctp_assembler"]
resolver = "2"
