[workspace]
members = ["binance", "binance_spot_connector", "binance_future_connector", "binance_spot_connector/examples", "binance_future_connector/examples",
    "common", "market", "trade" , "lib_assembler", "log", "ctp", "bybit_connector", "bybit_connector/examples", "bybit"]
resolver = "2"
