[package]
name = "market"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
crossbeam = "0.8.4"
chrono = "0.4.38"
common = { path = "../common" }
log = { path = "../log" }